### ISSUE TITLE
WAAgent Warning Status file too big

### ISSUE THREAD

**Issue by Klaas-** [Azure/LinuxPatchExtension#131]
I am receiving warnings in waagent log like:
`WARNING ExtHandler ExtHandler [PERIODIC] For Extension Handler Microsoft.CPlat.Core.LinuxPatchExtension-1.6.35 for the sequence number 1, the status file /var/lib/waagent/Microsoft.CPlat.Core.LinuxPatchExtension-1.6.35/status/1.status. Encountered the following error: [ExtensionStatusError] For Extension Handler Microsoft.CPlat.Core.LinuxPatchExtension-1.6.35 for the sequence number 1, the status file /var/lib/waagent/Microsoft.CPlat.Core.LinuxPatchExtension-1.6.35/status/1.status of size 141892 bytes is too big. Max Limit allowed is 131072 bytes`

Greetings
Klaas

**Comment by kjohn-msft** [comment]
We are aware of this reporting limitation in waagent hitting a few machines that have a large payload size of packages assessed and/or installed. We are actively exploring ways to get around this limitation, but in the near-term, it should get mitigated on its own on almost all of the few machines that get affected as packages get updated (and consequently the payload size decreases).

**Comment by kjohn-msft** [comment]
@feng-j678 has nearly completed addressing this through status truncation. It should go live before the end of the quarter.
