### ISSUE TITLE
Check sources.list.d files for check update on Ubuntu

### ISSUE THREAD

**Issue by nicolas-morel-claranet** [Azure/LinuxPatchExtension#175]
Hello,

We met an issue on Ubuntu Virtual machine, our configuration set all our repositories to the directory level /etc/sources.list.d .

But the update detection failed with this error:
`
2023-02-28T08:47:46Z> ERROR:EXCEPTION during patch operation: Exception('Unexpected return code (1) from command: sudo grep security /etc/apt/sources.list > /tmp/az-update-security.list', '')
`

This command work for us:
`root@localhost:/var/lib/waagent# sudo grep -ri security /etc/apt/sources.list.d/
/etc/apt/sources.list.d/XXXXX-distrib.list:## review or updates from the Ubuntu security team.
/etc/apt/sources.list.d/XXXXX-distrib.list:## security team.
/etc/apt/sources.list.d/XXXXX-distrib.list:## XXXXX Ubuntu jammy - Mirror of Official Security
/etc/apt/sources.list.d/XXXXX-distrib.list:deb [arch=amd64] http://XXXXX/ubuntu/ jammy-security main restricted
/etc/apt/sources.list.d/XXXXX-distrib.list:deb [arch=amd64] http://XXXXX/ubuntu/ jammy-security universe
/etc/apt/sources.list.d/XXXXX-distrib.list:deb [arch=amd64] http://XXXXX/ubuntu/ jammy-security multiverse
`

Version used: Microsoft.CPlat.Core.LinuxPatchExtension-1.6.42/MsftLinuxPatchCore.py

Can you update the script to check all files in sources.list.d and sources.list 
We can use this commande instead:
`root@localhost/var/lib/waagent/Microsoft.CPlat.Core.LinuxPatchExtension-1.6.42# sudo grep -Eh '^deb .*security' /etc/apt/sources.list /etc/apt/sources.list.d/*
`

https://github.com/Azure/LinuxPatchExtension/blob/938ab4c38202e63e0dc011a149d45d5a6f8db47a/src/core/src/package_managers/AptitudePackageManager.py#L40

Thank you

**Comment by nicolas-morel-claranet** [comment]
UP

Some news on this issue please

**Comment by kjohn-msft** [comment]
This has been covered in production. If there is any machine that's not picking up sources as expected, please let us know.
