### ISSUE TITLE
Output from package manager:  |	E: Type 'Types:' is not known on line 51 in source list

### ISSUE THREAD

**Issue by delriounicc** [Azure/LinuxPatchExtension#262]
**Describe the bug**
When I try to update my VM Ubuntu 22.04.4 LTS I couldn´t upgrade the updates with the classification "Other". It failed. I tried 2 times with the same error.
There were 10 updated not installed on the VM.
 The error that I could see on the logs was:
2024-07-17T06:57:48Z> [APM] Refreshing local repo... [Sources=/var/lib/waagent/Microsoft.CPlat.Core.LinuxPatchExtension-1.6.55/tmp/azgps-patch-custom-9c5d4163-b5ac-4ecc-a617-11492d9680d5.list]
	DEBUG: Invoking package manager using: sudo apt-get -q update -oDir::Etc::Sourcelist=/var/lib/waagent/Microsoft.CPlat.Core.LinuxPatchExtension-1.6.55/tmp/azgps-patch-custom-9c5d4163-b5ac-4ecc-a617-11492d9680d5.list
2024-07-17T06:57:48Z> [ERROR] Package manager was invoked using: sudo apt-get -q update -oDir::Etc::Sourcelist=/var/lib/waagent/Microsoft.CPlat.Core.LinuxPatchExtension-1.6.55/tmp/azgps-patch-custom-9c5d4163-b5ac-4ecc-a617-11492d9680d5.list
2024-07-17T06:57:48Z> WARNING:- Return code from package manager: 100
2024-07-17T06:57:48Z> WARNING:- Output from package manager:  |	E: Type 'Types:' is not known on line 51 in source list /var/lib/waagent/Microsoft.CPlat.Core.LinuxPatchExtension-1.6.55/tmp/azgps-patch-custom-9c5d4163-b5ac-4ecc-a617-11492d9680d5.list |	E: The list of sources could not be read.
2024-07-17T06:57:48Z> ERROR:[APM] Error in modifying custom sources list. [Error=Exception('Unexpected return code (100) from package manager on command: sudo apt-get -q update -oDir::Etc::Sourcelist=/var/lib/waagent/Microsoft.CPlat.Core.LinuxPatchExtension-1.6.55/tmp/azgps-patch-custom-9c5d4163-b5ac-4ecc-a617-11492d9680d5.list', '')]

**To Reproduce**
1. Run one-time update or scheduled update on a VM Ubuntu 22.04.4 LTS 

**Expected behavior**
The expected behaviour is that all the updates were successfully installed.

**Screenshots**
![image](https://github.com/user-attachments/assets/aa1253c5-836c-4b43-a31b-3df1cb7a9993)
![image](https://github.com/user-attachments/assets/b9d678c7-f135-456b-85bf-601b57ddb065)

**[patch_17072024.txt](https://github.com/user-attachments/files/16261840/patch_17072024.txt)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HotStew** [comment]
I have exactly the same problem. I was able to retrieve the source list file during the patch since it gets deleted afterwards.

Like for you, it fails on the `Types: deb` line. This got me wondering about the supported format of file type. Turns out the format being used in the `azgps-patch-custom-[UUID].list` file is the DEB822-style format, but this format is only supported by the `.sources` file extension but not the `.list` file extension as described [here in the manpage.](https://manpages.ubuntu.com/manpages/bionic/man5/sources.list.5.html)

Contents of the file:
```
## Note, this file is written by cloud-init on first boot of an instance
## modifications made here will not survive a re-bundle.
## if you wish to make changes you can:
## a.) add 'apt_preserve_sources_list: true' to /etc/cloud/cloud.cfg
##     or do the same in user-data
## b.) add sources in /etc/apt/sources.list.d
## c.) make changes to template file /etc/cloud/templates/sources.list.tmpl

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://azure.archive.ubuntu.com/ubuntu/ jammy main restricted
# deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://azure.archive.ubuntu.com/ubuntu/ jammy-updates main restricted
# deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://azure.archive.ubuntu.com/ubuntu/ jammy universe
# deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy universe
deb http://azure.archive.ubuntu.com/ubuntu/ jammy-updates universe
# deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://azure.archive.ubuntu.com/ubuntu/ jammy multiverse
# deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy multiverse
deb http://azure.archive.ubuntu.com/ubuntu/ jammy-updates multiverse
# deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://azure.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
# deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse

deb http://azure.archive.ubuntu.com/ubuntu/ jammy-security main restricted
# deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy-security main restricted
deb http://azure.archive.ubuntu.com/ubuntu/ jammy-security universe
# deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy-security universe
deb http://azure.archive.ubuntu.com/ubuntu/ jammy-security multiverse
# deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy-security multiverse
deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/ubuntu/22.04/prod jammy main
Types: deb
URIs: https://packages.microsoft.com/repos/azure-cli/
Suites: jammy
Components: main
Architectures: amd64
Signed-by: /etc/apt/keyrings/microsoft.gpg
```

**Comment by HotStew** [comment]
@rane-rajasi Could the fix be as simple as it seems? Just changing the file extension to `.sources`?

**Comment by HotStew** [comment]
@benank @feng-j678 ping

**Comment by juanantoniofornericc** [comment]
I was suffering same issue, I have been able to fix it by replacing /etc/apt/sources.list.d/azure-cli.source file with /etc/apt/sources.list.d/azure-cli.list, it looks like azure update manager agent picks all files from /etc/apt/sources.list.d and merges them into a single file called azgps-patch-custom-[UUID].list, meaning that it is mixing .list and .source formats in a single .list file, causing the process to fail. If you have any .source file in /etc/apt/sources.list.d I recommend you to convert it to a .list file and test again the patching process.

**Comment by MarioGruda** [comment]
We have the nearly same problem with Ubuntu 24.04.

`Output from package manager:  | E: Type 'Suites:' is not known on line 7 in source list`

instead of 'Types'

**Comment by MarioGruda** [comment]
We have the same problem with Ubutu 24.04 LTS (22.04 worked fine for us). We have the two files ‘ubuntu.sources’ and ‘microsoft-prod.list’ under /etc/apt/sources.list.d. When updating, though Azure Update Manager we get the error `Output from package manager: | E: Type ‘Suites:’ is not known in line 7 in the source list /var/lib/waagent/Microsoft.CPlat.Core.LinuxPatchExtension-1.6.55/tmp/azgps-patch-custom-ce60719a-f0b6-4dc7-b0a8-fcc10314f75d.list`. Running `apt upgrade` manually works fine. 

We have changed the sources file to the older list format and now it works again.

**Comment by janv8000** [comment]
Similar issue https://learn.microsoft.com/en-us/answers/questions/2082463/azure-patch-manager-error-code-(100)-ubuntu-24-04 ?

> E: Type 'URIs:' is not known on line 1 in source list /var/lib/waagent/Microsoft.SoftwareUpdateManagement.LinuxOsUpdateExtension-1.0.45.0/tmp/msft-aumc-security-patches-1d6d5e68-8f77-488b-9b23-d5f3ea923a45.list

**Comment by frans-otogone** [comment]
@kjohn-msft was this issue resolved somehow?

**Comment by janv8000** [comment]
https://github.com/Azure/LinuxPatchExtension/commit/530dec296cf8c0be7a0795e0f555d7605f4c4d11 mentions debstyle882 support

**Comment by kjohn-msft** [comment]
Yes, support for this is checked in and validated. It will only be deployed into production in January 2025 though because of end of year deployment blocks.

**Comment by Sachin311098** [comment]
Has this issue been resolved? Has Microsoft deployed a fix, and is there an eta for it?

**Comment by tjone270** [comment]
Hi, following up on the last comment from @Sachin311098, is there an update on this issue and if so, what's the ETA?

**Comment by olivebay** [comment]
Is there an ETA for this fix?

**Comment by justenh1431** [comment]
We are still waiting for the fix. Cannot update Ubuntu 24.04 VMs with Azure Update Manager without throwing an error.

**Comment by FabianKnapp** [comment]
Same here... still waiting for the fix.

**Comment by kjohn-msft** [comment]
Please create a brand-new machine in **West Central US** and review functionality for correctness. There have been Azure-wide changes in how deployments happen for all services and artifacts for improved safety that delayed the availability of this release publicly. The cadence of availability region to region will also be slower going forward for similar broadly mandated reasons. 

Depending on which region a VM may be in, availability can be as soon as the next couple of days or over the course of February. Existing machines will always get updated versions only sometime after new VMs created soon after a release is available in a region.

**Comment by emmasweety** [comment]
Can we have an update please? I have several ARC-joined Ubuntu boxes in Azure Update Manager that are still failing to apply updates.

**Comment by kjohn-msft** [comment]
> Can we have an update please? I have several ARC-joined Ubuntu boxes in Azure Update Manager that are still failing to apply updates.

Arc-joined Ubuntu machines are **not** primarily serviced by this code base. The improvements here will not accrue to Arc except in the very specific use case of 'automatic assessment' (running periodically by itself on VMs).

To be clear:
- All scenarios on Azure-hosted VMs - this code.
- Automatic Assessment on Arc - this code.
- Manual assessment, Install Patches on Arc - different extension; not open-source, owned by Azure Update Manager directly. 

Azure Update Manager relies on the Azure Linux Patch Extension for all core Azure scenarios and auto-assessment on Arc.

For the failures on **Arc**, you'll need to reach out to the Azure Update Manager through their official support channels.

All newly created VMs in **Azure**, this will function everywhere. For existing (older VMs), most regions would have the update too - if not yet, they should be covered by the first week of March.

**Comment by FabianKnapp** [comment]
> 
> For the failures on **Arc**, you'll need to reach out to the Azure Update Manager team through their official support channels.
> 

That is not customer-friendly and rather reflects a "not my business" mindset.

**Comment by justenh1431** [comment]
In our existing Ubuntu 24.04 Azure VMs Update Manager now completes without errors, so it seems to be fixed.

**Comment by DavidGarrana** [comment]
> Azure Update Manager relies on the Azure Linux Patch Extension for all core Azure scenarios and auto-assessment on Arc.
> 
> For the failures on **Arc**, you'll need to reach out to the Azure Update Manager team through their official support channels.
> 
@kjohn-msft As you probably know, it kills a major feature of Azure Arc on customers that are already using it and have Ubuntu 24.04 VMs (or any other Debian based Linux distribution or repository that uses Deb8222 format on sources.list.d) on other environments, including on premises, that is a scenario heavily advocated for customers on their transition to the Azure Cloud.

This bug is very trick to explain even to someone that actually uses Azure Update Manager on their operations, because it works on some scenarios (Azure VMs and Automatic Assessment on Arc) and the scenario where it doesn't work (Check for updates manually, Install the actual updates) includes the very purpose of Azure Update Manager.

Could you kindly point us to a channel where we can take this question to the team responsible for the code that actually updates packages on Arc machines so we can build upon what's here, instead of each of us, affected customers and CSPs, individually creating several dozen support tickets that will raise a multitude of questions from the customer support representatives that, with luck, someday, will meet the proper team that can make something about it?

For those of you who need an immediate workaround, I found this [tool](https://github.com/ErikMichelson/apt-deb822-tool), that converts files written in Deb822 format to the older list format AUM works with. It requires manual editing of files after conversion because it generates commented lines without line breaks. Also remove the .bak files it creates after because AUM reads all the files present on /etc/apt/sources.list.d unlike apt that only reads .list and .source ones.

**Comment by trevorstr** [comment]
Seems like a recurring theme in the Azure ecosystem:
 
- Run into obscure error message in Azure
- Do a Google search
- Find a random GitHub thread from months (or many years) ago
- Observe lots of discussion on the topic / customers asking for fix
- Fix promised at some point
- Fix still isn't available months later

---

So today, I figured I would try out Azure Arc, to see what it could do. I spun up a Linux VM on MacOS, using [Lima](https://github.com/lima-vm/lima) (highly recommended BTW), running Ubuntu 24.04 LTS. Then I ran the Azure Arc install script. After that, I tried to use the Update Manager in the Azure Portal. 

Got this error.

What now?

<img width="1379" alt="Image" src="https://github.com/user-attachments/assets/452ee222-d353-4744-b7a0-5880659d027a" />

```
Assessment failed due to this reason: Assessment completed with 1 errors
Unexpected return code (100) from package manager on command: LANG=en_US.UTF8 sudo apt-get -s dist-upgrade -oDir::Etc::Sourcelist=/var/lib/waagent/Microsoft.SoftwareUpdateManagement.LinuxOsUpdateExtension-1.0.50.0/tmp/msft-aumc-security-patches-85a6ce5f-d59d-4046-9038-8baaa9edac0f.list  and output: E: Type 'Suites:' is not known on line 7 in source list /var/lib/waagent/Microsoft.SoftwareUpdateManagement.LinuxOsUpdateExtension-1.0.50.0/tmp/msft-aumc-security-patches-85a6ce5f-d59d-4046-9038-8baaa9edac0f.list
E: The list of sources could not be read.
E: Type 'Suites:' is not known on line 7 in source list /var/lib/waagent/Microsoft.SoftwareUpdateManagement.LinuxOsUpdateExtension-1.0.50.0/tmp/msft-aumc-security-patches-85a6ce5f-d59d-4046-9038-8baaa9edac0f.list
E: The list of sources could not be read.
```

**Comment by janv8000** [comment]
As @kjohn-msft mentioned
> Manual assessment, Install Patches on Arc - different extension; not open-source, owned by Azure Update Manager directly.

> For the failures on Arc, you'll need to reach out to the Azure Update Manager team **through their official support channels.**

FWIW, I created an Azure support request with id 2504090050003579 .
And upvoted https://feedback.azure.com/d365community/idea/26bf2647-2c7f-ef11-a4e6-000d3a059eeb 😑

**Comment by DavidGarrana** [comment]
> 2504090050003579

Our is 2504030040012364, still ongoing.

**Comment by kjohn-msft** [comment]
@trevorstr **LinuxOsUpdateExtension** (not this repo) is a closed-source Arc-only extension that does not have support for debstyle sources yet. The best information I have is that most of the code is there and it will only have support in June 2025. 

**Azure\LinuxPatchExtension** (this repo) runs on all Azure VMs and provides auto-assessment support for Arc VMs (so automatic assessment will work there too). With up-to-date versions, you should not have any trouble with this in Azure or in the _automatic assessment_ scenario in Arc.

Thanks for sharing this link @janv8000 - https://feedback.azure.com/d365community/idea/26bf2647-2c7f-ef11-a4e6-000d3a059eeb

I will raise it with the Azure Update Manager team and have them set official expectations there.
